### ISSUE TITLE
Cellar-C2 min part size is 5MB

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/cellar-migration#3]
If an object got uploaded on Cellar-c1 using multipart upload and with parts size less than 5MB, we will try to replicate the same upload on Cellar-c2. Unfortunately it will fail because the entity is too small.

This gives as a result files that can't be synchronized. On the other hand, if we synchronize them without using multipart (or bigger parts), the `ETag` attribute will differ, leading to the file being always displayed as "need to be synchronized".

To avoid that behavior, we can re-introduce usage of `LastModified` attribute. If `LastModified` on source object is lower than on destination object, then we can assume the file didn't change since the last synchronization.

New comparison algorithm would be:
```
- If the source and destination file have the same key and size
- If file has an ETag containing a number of parts
  - If source part size is less than 5MB
    - If source LastModified > destination LastModified
      - then synchronize
```

**Comment by Xfennec** [comment]
That's the capstone! Full migration without any issue. Thanks a lot @BlackYoup 😉
